name: CPU checks
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - if: runner.os == 'macOS'
        run: brew install libomp
      - run: python -m pip install -e '.[dask,dev]'
      - run: ruff check .
      - run: pytest -q
